### ISSUE TITLE
Date and Time not being updated

### ISSUE THREAD

**Issue by dony71** [Nurgak/Internet-of-Things-Power-Meter#4]
Default shows UTC time
How to change to PST time?

**Comment by Nurgak** [comment]
I assume you're running your own Node-RED instance, you probably forgot to properly set the timezone of your Node-RED server. If you're using a setup similar to mine, on a Raspberry Pi running DietPi, type "date" in the console and you'll see the same date that is shown on the matrix.

To set the timezone type "dietpi-config" and look for that option, don't forget to reboot for it to take effect (or just restart Node-RED I guess).

**Comment by Nurgak** [comment]
The timezone is not modifiable on the module, this unnecessarily complicates the code as the logging is done on the server side anyway.
